
name: Heroku Deployment


on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  deploy-heroku:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Git user
      run: |
        git config --local user.email "kaungzinhein113@gmail.com"
        git config --local user.name "Kaung Zin Hein"

    - name: Push to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12 
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "volunteer-mern"
        heroku_email: "kaungzinhein113@gmail.com"
        appdir: "server"

